eclipse-tractusx/sig-release

- AUTHORS.md
- add optional authors.md file as stated in https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01/
- represent the authors and project leads for the community 
should look like, please check if the company name is written correctly
> chore: add authors file

- AUTHORS.md
- CONTRIBUTING.md
- NOTICE.md
- README.md
Remove broken link to GH org eclipse-tractusx and fixed link to sig-release (community → sig-release) in `CONTRIBUTING.md` and `NOTICE.md`. Small changes to wording in README.md.
> docs: remove/fix broken links to repos and wording

- README.md
- rename status description "Planning" into "Inbox"
> chore: rename Planning Status -> Inbox

- README.md
This PR adds a small section 'what can I expect' to our process description. It describes how we handle new feature and bug reports
> docs: add 'what can i expect' process description

- trg-checks-dashboard/internal/templating/tractusx.go
The GitHub client initialization always used an httpClient with OAuth authentication.
OAuth authentication can only be used if a GitHub PAT is provided. 
This change fixes hat and let's the GitHub client create it's own httpClient
fixes #38
> fix: only use oauth for GitHub client, if token set

- .tractusx
PR to add .tractusx metadata file with basic configuration + new flag helping identify supporting repository. The flag will be used by quality checks dashboard for better presentation of repositories.
> chore: tractusx metadata

- .tractusx
Little PR to adopt .tractusx metadata with regards to approach change having more general repository categorisation.
> fix: adopt .tractusx metadata to new repo categorisation

- trg-checks-dashboard/DEPENDENCIES
- trg-checks-dashboard/go.mod
- trg-checks-dashboard/go.sum
- update go version filepath-securejoin/v0.2.4
updates https://github.com/eclipse-tractusx/sig-infra/issues/288
needed for https://github.com/eclipse-tractusx/sig-release/security/dependabot/1
- `go get github.com/cyphar/filepath-securejoin@v0.2.4`
- update `dependencies` with before requested IP Reviews
> chore: update DEPENDENCIES and change version filepath-securejoin/v0.2.4

- .github/workflows/build-and-deploy-dashboard.yaml
- add one more option for the workflow run on manual trigger and on schedule should be defaulted to generic github-access-token.
> chore: add not required input for manuall run + set default to generated access-token

- trg-checks-dashboard/DEPENDENCIES
- trg-checks-dashboard/go.mod
- trg-checks-dashboard/go.sum
- update tractus-quality-check version to 0.7.3
- update DEPENDENCIES
updates https://github.com/eclipse-tractusx/sig-infra/issues/259
> chore: update version quality checks

- .github/workflows/build-and-deploy-dashboard.yaml
- modify default github_api_token
updates https://github.com/eclipse-tractusx/sig-infra/issues/263
> fix: build-and-deploy-dashboard.yaml with GitHub API token

- trg-checks-dashboard/internal/templating/tractusx.go
PR to fix the way archived repos are identified, they don't need to have .tractux metadata anymore.
> fix: archived repos detection

- trg-checks-dashboard/DEPENDENCIES
- trg-checks-dashboard/go.mod
- trg-checks-dashboard/go.sum
- trg-checks-dashboard/internal/templating/tractusx.go
- trg-checks-dashboard/web/templates/body.html.tmpl
PR to improve quality check tool errors displayed as tooltips in the quality dashboard. By adding html data option within the tooltip it allows using html tags like line breaks. Implementation facilitates Web as well as CLI based formatted error messages.
Updates https://github.com/eclipse-tractusx/sig-infra/issues/265
> fix: web errors formatting improvement

- trg-checks-dashboard/internal/templating/tractusx.go
PR to re-enable web error messages in the dashboard for quality checks.
> fix: re-enable quality check web error msg

- release-automation/internal/dashboard/tractusx.go
- release-automation/internal/helm/resource_mgmt_check.go
PR fixes rendering helm charts which contain subcharts within resources mgmt check.
updates https://github.com/eclipse-tractusx/sig-infra/issues/251
> fix: helm chart rendering

- release-automation/cmd/run_trg_checks.go
- release-automation/internal/dashboard/tractusx.go
- release-automation/internal/helm/chartyaml.go
- release-automation/internal/repo/default_branch.go
- release-automation/internal/repo/repo_structure_exists.go
- release-automation/internal/repo/repo_structure_exists_test.go
- release-automation/internal/repo/repoinfo.go
Fixes https://github.com/eclipse-tractusx/tractusx-quality-checks/issues/42
> fix: repo structure check

- release-automation/internal/container/allowed_base_image_check.go
PR to fix skip aligned base image check replacing used qual comparision by contains function. 
Reason for that is because dockerfilePath uses absolute path, however dockerfilesToSkip are relative paths (from metadata) hence if basedir was different than "." it doesn't work properly and required, configured dockerfiles are never skipped.
> fix: skip aligned base image check

- .github/ISSUE_TEMPLATE/3_product_release_checks.md
The subject matter experts do check their assigned issues rather than reading the comments in which they have been mentioned. In the release 24.03 this was unclear in some cases, this caused tasks that have been delayed.
> chore:included feedback from 24.03 release

- .github/ISSUE_TEMPLATE/3_product_release_checks.md
- README.md
This PR introduces better guidance for FOSS representatives to participate the release process.
> FOSS Product Template updated for release 24.05 

- release-notifier/README.md
PR to replace "TBP" placeholders of Kubernetes and PostgreSQL upgrade procedures and fix few markdown complains.
> docs(release-notifier): cosmetics + links update

- .github/workflows/release-notifier.yaml
PR to update current aligned kubernetes version to 1.28.9 of release notifier workflow.
> chore: bump k8s aligned version to 1.28.9

- README.md
- docs/open-refinement-and-planning.md
- docs/planning.md
- docs/product_release.md
- docs/tractus-x-release.md
This PR combines the content of the website and tractus-x-release repository into sig-release.
It thereby fixes the [Issue #572](https://github.com/eclipse-tractusx/sig-release/issues/572)
See:
- https://github.com/eclipse-tractusx/tractus-x-release/pull/26
- https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/852
Superseeds https://github.com/eclipse-tractusx/sig-release/pull/519
> add initial content for release consolidation

- docs/metadata_file.md
PR to update metadata file doc with description of new propriety to list product related OpenAPI specs for automation generating and publishing Swagger UI doc.
> docs: add OpenAPI spec section description to metadata file

- .github/ISSUE_TEMPLATE/3_product_release_checks.md
Removed checks for interoperability, data sovereignty and threat modeling because of changes in the process
> docs: update product release issue template

- .github/ISSUE_TEMPLATE/1_feature_template.md
Adapt the feature issue template. The message for the checkbox about commitment for implementation of the feature is adapted to be less pointed
> chore: Adapt feature template concerning implementation commitment message

- .github/ISSUE_TEMPLATE/5_KIT_template.md
Created KIT Issue Template with topics
- Description
- Impact
- KIT Team
- Architectural Relevance
> Create KIT Issue Template

- .github/workflows/release-notifier.yaml
As already communicated an upgrade to kubernetes version 1.33.1 was needed -> release-notifier update.
> chore(release-notifier): switch kubernetes version
